services:
  primary-mongodb: 
    extends:
      file: docker-compose-mongodb-replSet.yaml
      service: primary-mongodb
    volumes:
      - ./scripts/initialize-mongodb-replSet.sh:/scripts/initialize-mongodb-replSet.sh

  secondary-mongodb-1: 
    extends:
      file: docker-compose-mongodb-replSet.yaml
      service: secondary-mongodb-1

  secondary-mongodb-2: 
    extends:
      file: docker-compose-mongodb-replSet.yaml
      service: secondary-mongodb-2
